export default [
  { name: "after", isFunctional: false, },
  { name: "backdrop", isFunctional: false, },
  { name: "before", isFunctional: false, },
  { name: "cue", isFunctional: false, },
  { name: "cue-region", isFunctional: false, },
  { name: "first-letter", isFunctional: false, },
  { name: "first-line", isFunctional: false, },
  { name: "file-selector-button", isFunctional: false, },
  { name: "grammar-error", isFunctional: false, },
  { name: "marker", isFunctional: false, },
  { name: "part", isFunctional: true, },
  { name: "placeholder", isFunctional: false, },
  { name: "selection", isFunctional: false, },
  { name: "slotted", isFunctional: true, },
  { name: "spelling-error", isFunctional: false, },
  { name: "target-text", isFunctional: false, },
]
